export const deckData = [
  {
    boardCollection: "Code",
    skater: "McClung",
    company: "Plan B",
    width: "8.25",
    height: "31.77",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "Code",
    skater: "Joslin",
    company: "Plan B",
    width: "8.375",
    height: "31.71",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "Code",
    skater: "Gustavo",
    company: "Plan B",
    width: "8.0",
    height: "31.33",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "Code",
    skater: "Giraud",
    company: "Plan B",
    width: "8.125",
    height: "32.125",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "Diagonals",
    skater: "Fynn",
    company: "Plan B",
    width: "8.25",
    height: "31.77",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "Diagonals",
    skater: "Giraud",
    company: "Plan B",
    width: "8.0",
    height: "31.75",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "Diagonals",
    skater: "McClung",
    company: "Plan B",
    width: "8.25",
    height: "32.125",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "Diagonals",
    skater: "Joslin",
    company: "Plan B",
    width: "8.0",
    height: "31.75",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "ALF",
    skater: "Fynn",
    company: "Plan B",
    width: "8.25",
    height: "32.125",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "ALF",
    skater: "Giraud",
    company: "Plan B",
    width: "8.0",
    height: "31.75",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "ALF",
    skater: "Gustavo",
    company: "Plan B",
    width: "7.75",
    height: "31.625gustav",
    //   image: "https:faker.jpg",
  },
  {
    boardCollection: "ALF",
    skater: "Joslin",
    company: "Plan B",
    width: "8.0",
    height: "31.75",
    //   image: "https:faker.jpg",
  },
];
